using System.Collections.Generic;

namespace StJude2021
{
    class ModifierInfo
    {
        public static List<GameFlag> ModifierIndices { get; } = new List<GameFlag>()
        {
            // Cosplay occurs at the outside of the range, so it can be excluded when on cooldown.
            GameFlag.CosplayGiantDad,
            GameFlag.CosplayGwyn,
            GameFlag.CosplayHavel,
            GameFlag.CosplayMildred,
            GameFlag.CosplayUFC,
            GameFlag.CosplayCrystal,
            GameFlag.CosplayLogan,
            GameFlag.CosplayPharis,
            GameFlag.CosplayLaurentius,
            GameFlag.CosplayOswald,
            GameFlag.CosplayNoob,

            // Other modifiers.
            GameFlag.PatchesAmbush,
            GameFlag.ChannelerAmbush,
            GameFlag.EnemyAmbush,
            GameFlag.InvisibleWorld,
            GameFlag.WarpToManus,
            GameFlag.PraiseTheSun,
            GameFlag.ForestMode,
            GameFlag.DeathFollowsYou,
            GameFlag.WanderingEnemies,
            GameFlag.HyperAggression,
            GameFlag.GenderSwitch,
            GameFlag.TightCamera,
            GameFlag.WideCamera,
            GameFlag.InvertedCamera,
            GameFlag.RetroCamera,
            GameFlag.InvisiblePlayer,
            GameFlag.SummonGwyns,
            GameFlag.SummonBonewheels,
            GameFlag.PlayerSpeedUp,
            GameFlag.PlayerExtremeSpeedUp,
            GameFlag.PlayerSpeedDown,
            GameFlag.PlayerExtremeSpeedDown,
            GameFlag.PlayerHealthRegain,
            GameFlag.PlayerHealthDrain,
            GameFlag.PlayerMaxHealthUp,
            GameFlag.PlayerMaxHealthDown,
            GameFlag.PlayerStaminaRegenUp,
            GameFlag.PlayerExtremeStaminaRegenUp,
            GameFlag.PlayerStaminaRegenDown,
            GameFlag.PlayerMaxEquipLoadUp,
            GameFlag.PlayerMaxEquipLoadDown,
            GameFlag.PlayerDefenseUp,
            GameFlag.PlayerInvincible,
            GameFlag.PlayerDefenseDown,
            GameFlag.PlayerInstantDeath,
            GameFlag.PlayerExterminate,
            GameFlag.PlayerDetectionDown,
            GameFlag.PlayerSoulDrain,
            GameFlag.PlayerSturdy,
            GameFlag.PlayerFragile,
            GameFlag.PlayerWeakHeals,
            GameFlag.PlayerPainfulHeals,
            GameFlag.PlayerEggInfection,  // only causes head scratch
            GameFlag.PlayerBinocularsMode,
            GameFlag.PlayerThorny,
            GameFlag.PlayerFallControl,
            GameFlag.PlayerFireWeapon,
            GameFlag.PlayerMagicWeapon,
            GameFlag.PlayerLightningWeapon,
            GameFlag.PlayerFullHeal,
            GameFlag.PlayerOneHPPreHeal,
            GameFlag.PlayerSoulBoost,
            GameFlag.PlayerSoulSteal,
            GameFlag.EnemySpeedUp,
            GameFlag.EnemyExtremeSpeedUp,
            GameFlag.EnemySpeedDown,
            GameFlag.EnemyExtremeSpeedDown,
            GameFlag.EnemyHealthRegain,
            GameFlag.EnemyMaxHealthUp,
            GameFlag.EnemyMaxHealthDown,
            GameFlag.EnemyDefenseUp,
            
            // End of unique modifiers.
            // These slots are used as repeats to increase odds of certain modifiers.
            GameFlag.PatchesAmbush,
            GameFlag.ChannelerAmbush,
            GameFlag.EnemyAmbush,
            GameFlag.InvisibleWorld,
            GameFlag.WanderingEnemies,
            GameFlag.HyperAggression,
            GameFlag.HyperAggression,
            GameFlag.WanderingEnemies,
            GameFlag.WanderingEnemies,
            GameFlag.TightCamera,
            GameFlag.InvisiblePlayer,
            GameFlag.SummonGwyns,
            GameFlag.SummonBonewheels,
            GameFlag.EnemySpeedUp,
            GameFlag.PlayerWeakHeals,
            GameFlag.PlayerPainfulHeals,
            GameFlag.ChannelerAmbush,

            // Cosplay repeats.
            GameFlag.CosplayGiantDad,
            GameFlag.CosplayGwyn,
            GameFlag.CosplayHavel,
            GameFlag.CosplayMildred,
            GameFlag.CosplayUFC,
            GameFlag.CosplayCrystal,
            GameFlag.CosplayLogan,
            GameFlag.CosplayPharis,
            GameFlag.CosplayLaurentius,
            GameFlag.CosplayOswald,
            GameFlag.CosplayNoob,
        };

        public static Dictionary<GameFlag, string> ModifierNames = new Dictionary<GameFlag, string>()
        {
            [GameFlag.PatchesAmbush] = "Uncharitably Done",
            [GameFlag.ChannelerAmbush] = "Dance Dance Dance",
            [GameFlag.EnemyAmbush] = "Gravelord Ambush",
            [GameFlag.InvisibleWorld] = "There Is No Spoon",
            [GameFlag.WarpToManus] = "Manus Catalyst",
            [GameFlag.PraiseTheSun] = "Praise the Sun!",
            [GameFlag.ForestMode] = "Magic Beans...",
            [GameFlag.DeathFollowsYou] = "Death Follows You",
            [GameFlag.WanderingEnemies] = "Wandering Enemies...",
            [GameFlag.HyperAggression] = "Aggressive Enemies",
            [GameFlag.GenderSwitch] = "Gender Switch",
            [GameFlag.TightCamera] = "Tunnel Vision",
            [GameFlag.WideCamera] = "Shrooms",
            [GameFlag.InvertedCamera] = "Upside Down",
            [GameFlag.RetroCamera] = "Resident Evil Mode",
            [GameFlag.InvisiblePlayer] = "Invisible Player",
            [GameFlag.SummonGwyns] = "GWYN",
            [GameFlag.SummonBonewheels] = "Oops! All Bonewheels",
            [GameFlag.CosplayGiantDad] = "Giant Dad Cosplay",
            [GameFlag.CosplayGwyn] = "Gwyn Cosplay",
            [GameFlag.CosplayHavel] = "Havel Cosplay",
            [GameFlag.CosplayMildred] = "Mildred Cosplay",
            [GameFlag.CosplayUFC] = "UFC Cosplay",
            [GameFlag.CosplayCrystal] = "Crystal Cosplay",
            [GameFlag.CosplayLogan] = "Logan Cosplay",
            [GameFlag.CosplayPharis] = "Pharis Cosplay",
            [GameFlag.CosplayLaurentius] = "Laurentius Cosplay",
            [GameFlag.CosplayOswald] = "Oswald Cosplay",
            [GameFlag.CosplayNoob] = "Noob Cosplay",
            [GameFlag.PlayerSpeedUp] = "Speed Up",
            [GameFlag.PlayerExtremeSpeedUp] = "Speed Way Up",
            [GameFlag.PlayerSpeedDown] = "Speed Down",
            [GameFlag.PlayerExtremeSpeedDown] = "Speed Way Down",
            [GameFlag.PlayerHealthRegain] = "Health Regen",
            [GameFlag.PlayerHealthDrain] = "Health Drain",
            [GameFlag.PlayerMaxHealthUp] = "Max Health Up",
            [GameFlag.PlayerMaxHealthDown] = "Max Health Down",
            [GameFlag.PlayerStaminaRegenUp] = "Stamina Regen Up",
            [GameFlag.PlayerExtremeStaminaRegenUp] = "Stamina Regen Way Up",
            [GameFlag.PlayerStaminaRegenDown] = "Stamina Regen Down",
            [GameFlag.PlayerMaxEquipLoadUp] = "Equip Load Up",
            [GameFlag.PlayerMaxEquipLoadDown] = "Equip Load Down",
            [GameFlag.PlayerDefenseUp] = "Defense Up",
            [GameFlag.PlayerInvincible] = "Invincible!",
            [GameFlag.PlayerDefenseDown] = "Defense Down",
            [GameFlag.PlayerInstantDeath] = "Instant Death",
            [GameFlag.PlayerExterminate] = "Exterminator",
            [GameFlag.PlayerDetectionDown] = "Stealthy",
            [GameFlag.PlayerSoulDrain] = "Soul Drain",
            [GameFlag.PlayerSturdy] = "Sturdy",
            [GameFlag.PlayerFragile] = "Like a Leaf",
            [GameFlag.PlayerWeakHeals] = "Diluted Estus",
            [GameFlag.PlayerPainfulHeals] = "Poisoned Estus",
            [GameFlag.PlayerEggInfection] = "Head Scratcher",
            [GameFlag.PlayerBinocularsMode] = "Binoculars Mode",
            [GameFlag.PlayerThorny] = "Hedgehog Mode",
            [GameFlag.PlayerFallControl] = "Fall Control",
            [GameFlag.PlayerFireWeapon] = "Charcoal Resin",
            [GameFlag.PlayerMagicWeapon] = "Magic Weapon",
            [GameFlag.PlayerLightningWeapon] = "Gold Pine Resin",
            [GameFlag.PlayerFullHeal] = "Full Heal",
            [GameFlag.PlayerOneHPPreHeal] = "One HP",
            [GameFlag.PlayerSoulBoost] = "Soul Gift",
            [GameFlag.PlayerSoulSteal] = "Soul Steal",
            [GameFlag.EnemySpeedUp] = "Enemy Speed Up",
            [GameFlag.EnemyExtremeSpeedUp] = "Enemy Speed Way Up",
            [GameFlag.EnemySpeedDown] = "Enemy Speed Down",
            [GameFlag.EnemyExtremeSpeedDown] = "Enemy Speed Way Down",
            [GameFlag.EnemyHealthRegain] = "Enemy Health Regain",
            [GameFlag.EnemyMaxHealthUp] = "Enemy Max Health Up",
            [GameFlag.EnemyMaxHealthDown] = "Enemy Max Health Down",
            [GameFlag.EnemyDefenseUp] = "Enemy Defense Up",
        };
    }
}
